- name: Install Docker CE
  hosts: neo4j
  become: yes
  tasks:
    - include_role:
        name: docker

- name: Install Docker Compose
  hosts: neo4j
  become: yes
  tasks:
    - include_role:
        name: docker_compose

- name: Deploy Services
  hosts: neo4j
  become: yes
  tasks:
    - include_role:
        name: services_deployment