#!/usr/bin/env ansible-playbook

- name: Enable file output of data collectors
  hosts: bitflow-collector
  tasks:
    - include_role:
        name: ../../roles/bitflow-collector
        tasks_from: enable-data-collection

- name: Enable file output of client statistics
  hosts: client
  tasks:
    - uri:
        url: "http://0.0.0.0:{{ rtmp.client_api_port }}/api/file_output"
        timeout: 120
        method: POST
