
collector:
  image: bitflowstream/bitflow-collector:latest
  container_name: bitflow-collector
  path: /opt/bitflow-collector
  path_mounted: /opt/bitflow-collector

  http_data_port: 8050
  api_port: 8051

  libvirt:
    socket: /var/run/libvirt
    socket_mounted: /var/run/libvirt

  kube_namespace: default

  extra_args: ""
