#!/usr/bin/env ansible-playbook

- name: Set collector anomaly tag
  hosts: all:!sippstress:!etcd:!swarm_manager
  vars:
    anomaly_name: "cw-cassandra_node-0.ims4|corrupt_db"
  tasks:
    - name: Set collector anomaly tag
      uri:
        url: "{{ item }}"
        method: PUT
      with_items:
        - "http://0.0.0.0:{{ collector.api_port }}/api/tags?target={{ anomaly_name }}"
