version: '3.6'
services:
  neo4j:
    image: neo4j
    environment: # to read more about env variables: https://neo4j.com/docs/operations-manual/current/installation/docker/
      - NEO4J_AUTH=none   #none for no passwor. use neo4j/<password> to provide password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes  # to accept the license agreement
      - NEO4J_HEAP_MEMORY=1024
      - NEO4J_CACHE_MEMORY=1G
      #to specify other settings related to clusters, please see: https://neo4j.com/docs/operations-manual/current/installation/docker/ . But clustering seems to be  available only for enterprise addition 
    volumes:
      - ${HOME}/neo4j/data:/data #for data storage. home:  /var/lib/neo4j, path:  /var/lib/neo4j/data
      #- ${HOME}/neo4j/logs:/logs #for logs. home:  /var/lib/neo4j, path:  /var/lib/neo4j/logs
      #- ${HOME}/neo4j/conf:/conf #for conf. home:  /var/lib/neo4j, path:  /var/lib/neo4j/conf
    
    ports: # to read more about neo4j ports: https://neo4j.com/docs/operations-manual/current/configuration/ports/
      - "7474:7474"  # for http
      - "7687:7687"  # for bolt
      - "7473:7473" # for https
    network_mode: "host"
  neo4j_service:
    image: muhammadimran/openstack-neo4j-service
    depends_on:
      - "neo4j"
    environment:
      - GRAPHDB_URI=${GRAPHDB_URI}
      - GRAPHDB_USER=${GRAPHDB_USER}
      - GRAPHDB_PASS=${GRAPHDB_PASS}
    network_mode: "host"
  openstack_querier:
    image: muhammadimran/openstack-querier
    depends_on:
      - "neo4j"
      - "neo4j_service"
    volumes:
      - ${HOME}/.ssh/cit.key:/private_key.key
    network_mode: "host"
    env_file:
      - .env