
- name: retrieve swarm node names
  shell: "docker node ls --format '{{ '{{' }} .Hostname {{ '}}' }}' | tr ' ' '\n'"
  register: swarm_host_name

#- debug: var=item.split('-')[1]
#  with_items: "{{ swarm_host_name.stdout_lines }}"

- name: add a label to swarm nodes
  shell: docker node update --label-add comp={{ item.split('-')[1] }} {{ item }}
  with_items: "{{ swarm_host_name.stdout_lines }}"
  when: item is defined and item != ""
